# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "jakewendt-test_with_verbosity"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George 'Jake' Wendt"]
  s.date = "2014-08-08"
  s.description = "test_with_verbosity"
  s.email = "github@jakewendt.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/jakewendt-test_with_verbosity.rb",
    "lib/test_with_verbosity.rb"
  ]
  s.homepage = "http://github.com/jakewendt/test_with_verbosity"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "test_with_verbosity"
end

