# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: jakewendt-test_with_verbosity 0.0.5 ruby lib

Gem::Specification.new do |s|
  s.name = "jakewendt-test_with_verbosity".freeze
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["George 'Jake' Wendt".freeze]
  s.date = "2017-04-03"
  s.description = "test_with_verbosity".freeze
  s.email = "github@jakewendt.com".freeze
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/jakewendt-test_with_verbosity.rb",
    "lib/test_with_verbosity.rb"
  ]
  s.homepage = "http://github.com/jakewendt/test_with_verbosity".freeze
  s.rubygems_version = "2.5.2".freeze
  s.summary = "test_with_verbosity".freeze
end

